// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in ent-three-layer/app/user/srv/data/v1/do/ent/runtime.go

const (
	Version = "v0.12.4"                                         // Version of ent codegen.
	Sum     = "h1:LddPnAyxls/O7DTXZvUGDj0NZIdGSu317+aoNLJWbD8=" // Sum of ent codegen.
)
